version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: catalyst_mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Soccer.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - catalyst_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Catalyst Players API
  catalyst-api:
    build: .
    container_name: catalyst_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - catalyst_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: catalyst_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - catalyst-api
    networks:
      - catalyst_network

volumes:
  mysql_data:

networks:
  catalyst_network:
    driver: bridge 